// Generated by scripts/icons.mjs. Do not edit.
export const TOKEN_ICON_VERSION = "3e2631f3";
// Tokens with an icon in public/icons/tokens. Anything absent renders as a
// lettered badge, which beats a wrong logo.

export const TOKEN_ICONS = new Set<string>([
  "AAVE",
  "ADA",
  "APT",
  "ARB",
  "AVAX",
  "BNB",
  "BTC",
  "DOGE",
  "ETH",
  "FET",
  "FIL",
  "LDO",
  "LINK",
  "MATIC",
  "MKR",
  "NEAR",
  "OP",
  "PEPE",
  "RENDER",
  "SHIB",
  "SOL",
  "SUI",
  "TAO",
  "UNI",
  "USDC",
  "USDT",
  "WBTC",
  "XRP",
]);
